# application-docker.yml
spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/taskdb
  redis:
    host: redis
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# Logging configuration
logging:
  level:
    com.company.app: DEBUG
    org.springframework.data.mongodb: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always